apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name}}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Release.Name}}"
spec:
  ports:
  - port: {{ .Values.redis_stack_server.port }}
    name: db
  type: NodePort
  selector:
    app: "{{ .Release.Name}}"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name}}"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name}}" 
  serviceName: "{{ .Release.Name}}"
  replicas: {{ .Values.redis_stack_server.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name}}" 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: "{{ .Release.Name}}"
        image: {{ .Values.redis_stack_server.image }}:{{ .Values.redis_stack_server.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.redis_stack_server.port }}
          name: db
        volumeMounts:
        - name: db
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.redis_stack_server.storage_class }}
      resources:
        requests:
          storage: {{ .Values.redis_stack_server.storage }}
