apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  {{- if eq .Values.service.type "NodePort" }}
  type: NodePort
  {{- else if eq .Values.service.type "LoadBalancer" }}
  type: LoadBalancer
  {{- end }}
